[SQUASH]sdm845-common: bluetooth: Add unified bdroid header
sdm845-common: bluetooth:  Add unified bdroid header

Co-authored-by: chandu078 <chandudyavanapelli03@gmail.com>
Signed-off-by: durgesh33 <dgagoria3@gmail.com>

sdm845-common: bluetooth: Switch to a map based BT name

Change-Id: I6e0457441c5d2e7fd936d117439a90ae84496dc2
Signed-off-by: durgesh33 <dgagoria3@gmail.com>

sdm845-common: bluetooth: Fix undefined PROPERTY_VALUE_MAX

 * vendor/qcom/opensource/commonsys/bluetooth_ext/system_bt_ext/bta/swb/bta_ag_swb.cc:142:14: error: use of undeclared identifier 'PROPERTY_VALUE_MAX'
   char value[PROPERTY_VALUE_MAX];

Change-Id: Iaa9458296d71feacc88f5f04d7f5b99616115f23
Signed-off-by: durgesh33 <dgagoria3@gmail.com>

sdm845-common: bluetooth: Disable clean turn on

* This isn't needed anymore.

Change-Id: Ib77e5212099d82bbc07aea6044eb35109faff5cb
Signed-off-by: durgesh33 <dgagoria3@gmail.com>